### ISSUE TITLE
refactoring solutions to remove .querySelector()

### ISSUE THREAD

**Issue by rachaelcodes** [foundersandcoders/DOM-manipulation-Challenge#4]
.querySelector() is not always useful, as it doesn't update. Maybe we could refactor the solutions branch to include better query selectors.

**Comment by zurda** [comment]
Thanks @rachaelcodes  ! We'll fix this before FAC_16

**Comment by zurda** [comment]
Hi @rachaelcodes , thanks for pointing this out. 
I might be wrong, but the way I see this lesson is we want to show the students the different ways to select an element from the DOM. I agree I always use "getElementById" and "...ByClassName", but I think showing "querySelector" is still useful since you do come across it as a developer. 

I do think we could clarify this option better. Do you think adding a clarification about the difference between the three would address this issue?  we could explains the downsides of the different options.

**Comment by oliverjam** [comment]
Interesting. I literally only use `querySelector()` because it's the newest and most consistent API for getting DOM elements.

If anything I'd say the consistent/static nature of a NodeList is an advantage compared to the live HTMLCollection that the `getByX` methods return. It's easier for beginners and closer to how normal functions work (return values don't normally change later on in your code).

It might be at least worth clarifying the difference in the README, but I wouldn't rewrite the solutions.

I actually just wrote up a whole [intro to DOM manipulation](https://hackmd.io/aRe39cHGQr-NsG7UrELHmA), but it only covers `querySelector`, since you can do everything with just that.

**Comment by oliverjam** [comment]
I just had a look at the README for this repo and can see a few wording changes I think would help. I can do a PR later today if that would help?

**Comment by zurda** [comment]
That would be awesome, @oliverjam , Thanks! 
Personally, I find adding a clarification makes sense since I really enjoyed learning the different ways to do the same things. I think having multiple solutions is something that comes up a lot in JS (and specifically in this week's project) so keeping that variety in the workshop solution makes sense, I think. 
If you're changing the wording, I suggested another tiny edit in #8, but nothing crucial.

**Comment by oliverjam** [comment]
Added a clarification about the difference between a live HTMLCollection and a static NodeList in #9
